application: blacktree-secrets
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images

- url: /load
  script: myloader.py
  
- url: /.*
  script: helloworld.py