application: blacktree-secrets
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: static/stylesheets

- url: /javascript
  static_dir: static/javascript

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
    
- url: /images
  static_dir: static/images

- url: /load
  script: myloader.py
  
- url: /.*
  script: secrets.py